// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5BE3H4P-pB9-Sc04OFKGrafo2uELnPvM',
    appId: '1:859156011273:web:5112a0272b5f4fde0d9bd8',
    messagingSenderId: '859156011273',
    projectId: 'whatsapp-clone-7d2d7',
    authDomain: 'whatsapp-clone-7d2d7.firebaseapp.com',
    storageBucket: 'whatsapp-clone-7d2d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPb2eqahnjnt8NLV_EnKINqaepIga_CU',
    appId: '1:859156011273:android:8cba36495f8067ff0d9bd8',
    messagingSenderId: '859156011273',
    projectId: 'whatsapp-clone-7d2d7',
    storageBucket: 'whatsapp-clone-7d2d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJCvbpZJYvm7kD2nsJuffWYLvK7PsQBQ',
    appId: '1:859156011273:ios:76883b3044a53edc0d9bd8',
    messagingSenderId: '859156011273',
    projectId: 'whatsapp-clone-7d2d7',
    storageBucket: 'whatsapp-clone-7d2d7.appspot.com',
    iosClientId: '859156011273-5krlgl8u0vmt1vbhlte4j4a4ts16gm2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
